### ISSUE TITLE
About setting unicode locale on instructions

### ISSUE THREAD

**Issue by falcaopetri** [pwn2winctf/PTE#4]
Currently, the setup instruction says this:
```bash
Please make sure you are using an Unicode locale, e.g.
export LC_ALL=en_US.UTF-8
```

Changing the default encoding could possibly break third party code, as described at [Why sys.setdefaultencoding() will break code](https://anonbadger.wordpress.com/2015/06/16/why-sys-setdefaultencoding-will-break-code/) (at _(1) Write once, change everything_). 

**I suppose that's not a big issue in this project**. Anyway, the consensus seems to be that we should **explicitly** convert input and output to/from unicode, always manipulating unicode inside our code, and always checking UnicodeEncodeError.

Just for reference, the env var [PYTHONIOENCODING]((https://docs.python.org/2/using/cmdline.html#envvar-PYTHONIOENCODING)) controls the encoding used by std{in,out,err}, so we don't need to use LC_ALL if we just want to set the stds' encoding.

So an alternative to the current setup, would be renaming `ctf` to something like `ctf.py`, and make `ctf` a bash script calling something like: `PYTHONIOENCODING=UTF-8 ./ctf.py "$@"`.

If we want to change the enconding inside the code, we could do the following (reference: [Encoding of Python stdout](http://www.macfreek.nl/memory/Encoding_of_Python_stdout#StreamWriter_Wrapper_around_Stdout)): 

```python
if sys.stdout.encoding != 'UTF-8':
    if PY2:
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout, 'strict')
    else:
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
```

Apparently the writer returned does not have the endline buffering like the default stdout (not tested), but this should be irrelevant. Everything else works as expected.

I'm not sure if exporting LC_ALL makes the terminal more likely to display unicode, if supported. Gnome-terminal seems to not allow pasting unicode symbols if LC_ALL=C, although it still displays them when printed from python code.

If we want to support Windows, we may need even more setup, changing even the default font of cmd. I've got some reference links if you want.

**Comment by thotypous** [comment]
Thanks for the detailed summary on this issue. Perhaps we could just emit a warning to the user if `sys.stdout.encoding != 'UTF-8'`, asking they to set an unicode locale. Then we could maybe move the instructions from the README to this warning.
